# Generated by Django 6.0 on 2026-01-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_firebase_uid_alter_category_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.note')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('note', 'version_number')},
            },
        ),
    ]
